pub(crate) mod agile;
pub(crate) mod holistic;
pub(crate) mod home;
pub(crate) mod interviews;
pub(crate) mod simple;
pub(crate) mod standards;
pub(crate) mod statement_of_work;
pub(crate) mod tenets;
pub(crate) mod tests;

pub(crate) use agile::*;
pub(crate) use holistic::*;
pub(crate) use home::*;
pub(crate) use interviews::*;
pub(crate) use simple::*;
pub(crate) use standards::*;
pub(crate) use statement_of_work::*;
pub(crate) use tenets::*;
pub(crate) use tests::*;
